title: All-Star ME
logo: /assets/img/allstar.png
email: mellgass@gmail.com
description: 
  'Cause it's a long road to wisdom
  But it's a short one to being ignored
show_downloads: false
google_analytics: 
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
