title: All-Star ME
logo: /assets/img/allstar.png
email: mellgass@gmail.com
description: 
  My name is Ozymandias, King of Kings;
  Look on my Works, ye Mighty, and despair!
  Nothing beside remains. Round the decay
  Of that colossal Wreck, boundless and bare
  The lone and level sands stretch far away.
show_downloads: false
google_analytics: 
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
